version: "3.9"

name: daytrader-microservices

services:
  web-service:
    image: quay.io/daytrader/daytrader-web-service:latest
    hostname: web-service
    container_name: daytrader-web-service
    networks: 
      - dev
    ports:
      - "5443:5443"

  gateway-service:
    image: quay.io/daytrader/daytrader-gateway-service:latest
    hostname: gateway-service
    container_name: daytrader-gateway-service
    networks: 
      - dev
    ports:
      - "2443:2443"

  portfolios-service:
    image: quay.io/daytrader/daytrader-portfolios-service:latest
    hostname: portfolios-service
    container_name: daytrader-portfolios-service
    networks: 
      - dev
    ports:
      - "3443:3443"

  quotes-service:
    image: quay.io/daytrader/daytrader-quotes-service:latest
    hostname: quotes-service
    container_name: daytrader-quotes-service
    networks: 
      - dev
    ports:
      - "4443:4443"


  accounts-service:
    image: quay.io/daytrader/daytrader-accounts-service:latest
    hostname: accounts-service
    container_name: daytrader-accounts-service
    networks: 
      - dev
    ports:
      - "1443:1443"

networks:
  dev: