apiVersion: v1
kind: Service
metadata:
  name: daytrader-portfolios-service
  namespace: daytrader
spec:
  selector:
    app: daytrader-portfolios
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  {{ if .Values.nodeport }}
  type: NodePort
  {{ else }}
  type: ClusterIP
  {{ end }}
---
{{if .Values.ocCreateRoute}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: daytrader-portfolios-service
spec:
  to:
    kind: Service
    name: daytrader-portfolios-service
{{end}}